name: cocoscore
channels:
- defaults
- conda-forge
dependencies:
- xgboost=0.6a2
- nltk=3.2.4
- numpy=1.13.3
- pandas=0.20.3
- python=3.6.1
- scikit-learn=0.19.1
- scipy=0.19.1
- pip:
  - boto==2.38.0
  - gensim==3.0.1

