name: cocoscore
channels:
- defaults
- conda-forge
dependencies:
- fasttext=0.1.0
- xgboost=0.6a2
- matplotlib=2.1.0
- nltk=3.2.4
- numpy=1.13.3
- pandas=0.20.3
- python=3.6.1
- scikit-learn=0.19.1
- scipy=0.19.1
- seaborn=0.8.0
- pip:
  - gensim==3.0.1

