name: test-environment
channels:
- defaults
dependencies:
- xgboost=0.6a2=py36_0
- nltk=3.2.2=py36_0
- numpy=1.12.1=py36_0
- pandas=0.19.2=np112py36_1
- python=3.6.1=0
- scikit-learn=0.18.1=np112py36_1
- scipy=0.19.0=np112py36_0
- pip:
  - gensim==3.0.1

